### ISSUE TITLE
Assert in json.c looks suspicious

### ISSUE THREAD

**Issue by maneeshm** [ensc/xmlrpc-c#1]
https://github.com/ensc/xmlrpc-c/blob/master/src/json.c#L826

assert(tokP->type = typeString);

Thanks!

**Comment by ensc** [comment]
true; but should be reported upstream (http://xmlrpc-c.sourceforge.net/downloading.php).  This repo was used for local changes to xmlrpc-c and is inactive (--> not synced with upstream) for some years.
